config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'items#index'

  resources :items do
    member do
      patch :complete
    end
  end

  get 'welcomepage', to: 'welcomepage#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
# == Schema Information
#
# Table name: items
#
#  id           :bigint           not null, primary key
#  completed_at :datetime
#  description  :text
#  title        :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  user_id      :bigint
#
# Indexes
#
#  index_items_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Item < ApplicationRecord
  belongs_to :user

  def completed?
    completed_at.present?
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  has_many :items

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
# frozen_string_literal: true

class ItemsController < ApplicationController
  before_action :check_user_signed_in
  before_action :set_item, only: %i[show edit update destroy]

  def index
    @items = Item.where(user_id: current_user.id).order(created_at: :desc)
  end

  def new
    @item = current_user.items.build
  end

  def show; end

  def create
    @item = current_user.items.build(item_params)
    if @item.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @item.update(item_params)
      redirect_to item_path(@item)
    else
      render :edit
    end
  end

  def destroy
    @item.destroy
    redirect_to root_path
  end

  def complete
    @item = Item.find(params[:id])
    @item.update(completed_at: Time.zone.now)
    redirect_to root_path
  end

  private

  def check_user_signed_in
    redirect_to welcomepage_path unless user_signed_in?
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:title, :description)
  end
end

app/controllers/welcomepage_controller.rb
# frozen_string_literal: true

class WelcomepageController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= simple_form_for @item do |f| %>
  <%= f.input :title, label: 'Item Title' %>
  <%= f.input :description %>
  <%= f.button :submit %>
<% end %>

app/views/items/edit.html.erb
<div class="row">
  <div class="offset-md-2 col-md-8">
    <h2>Edit Todo Item</h2>
    <%= render 'form'  %>
  </div>
</div>

app/views/items/index.html.erb
<div class="offset-md-1 col-md-10">
  <% @items.each do |item| %>
    <div class="index-wrapper">
      <% if item.completed? %>
        <div class="row item">
          <div class="col-md-2">
            <p>
              <%= link_to complete_item_path(item), method: :patch do %>
                <i class="fas fa-check fa-lg"></i>
              <% end %>
            </p>
          </div>
          <div class="col-md-2">
            <p>
              <%= link_to item, method: :delete, data: { confirm: "Are you sure=" } do %>
                <i class="fas fa-trash fa-lg"></i>
              <% end %>
            </p>
          </div>
          <div class="col-md-8">
            <h2 style="opacity: 0.5; text-decoration: line-through;" class="item-title"><%= link_to item.title, item %></h2>
            <p style="opacity: 0.5;" class="item-sub-title item-desc"><%= item.description %></p>
            <p style="opacity: 0.5;" class="time-created-at item-sub-title">
              <%= "Completed #{time_ago_in_words(item.completed_at)} ago" %>
            </p>
          </div>
        </div>
      <% else %>
        <div class="row item">
          <div class="col-md-2">
            <p>
              <%= link_to complete_item_path(item), method: :patch do %>
                <i class="fas fa-check fa-lg"></i>
              <% end %>
            </p>
          </div>
          <div class="col-md-8">
            <h2 class="item-title"><%= link_to item.title, item %></h2>
            <p class="item-sub-title item-desc"><%= item.description %></p>
            <p style="opacity: 0.5;" class="time-created-at item-sub-title">
              <%= "Created #{time_ago_in_words(item.created_at)} ago" %>
            </p>
          </div>
          <div class="col-md-2">
            <p>
              <%= link_to item, method: :delete, data: { confirm: "Are you sure=" } do %>
                <i class="fas fa-trash fa-lg"></i>
              <% end %>
            </p>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/items/new.html.erb
<div class="row">
  <div class="offset-md-2 col-md-8">
    <h2>New Todo Item</h2>
    <%= render 'form'  %>
  </div>
</div>

app/views/items/show.html.erb
<div class="row">
  <div class="offset-md-1 col-md-10">
    <h2><%= @item.title %></h2>
    <p><%= @item.description %></p>
  </div>
</div>
<div class="row">
  <div class="offset-md-4 col-md-4">
    <%= link_to 'back', root_path, class:'btn btn-primary' %>
    <%= link_to 'Edit', edit_item_path(@item), class: 'btn btn-warning' %>
    <%= link_to 'Delete', item_path(@item), method: :delete, data: { cofirm: 'Are you sure?' }, class: 'btn btn-danger' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hiptime</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<nav class="navbar navbar-expand-lg bg-body-secondary">
  <div class="container-fluid">
    <%= link_to 'Hiptime', root_path, class: 'navbar-brand' %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Create Item', new_item_path, class:'nav-link' %>
          </li>
        <% end %>
        <!--<li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li>
              <hr class="dropdown-divider">
            </li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>-->
      </ul>
      <ul class="navbar-nav right-bar d-flex" role="search">
        <!--<input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">-->
        <!--<button class="btn btn-outline-success" type="submit">Search</button>-->
        <li class="nav-item">
          <% if current_user.present? %>
            <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
          <% else %>
            <%= link_to 'Log in', new_user_session_path, class: 'nav-link' %>
            <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>
</div>
</body>
</html>

app/views/welcomepage/index.html.erb
<div class="p-5 mb-4 bg-light rounded-3">
  <div class="container-fluid py-5 jumbotron">
    <h1 class="display-5 fw-bold">HipTime! Free and Easy</h1>
    <p class="col-12 fs-4">Trusted by Millions. Hiptime is the best online Task Management App!</p>
    <%= link_to 'Sign Up Now', new_user_registration_path, class:'btn btn-danger btn-lg' %>
  </div>
</div>